/**
 * Restaurant content archetypes -- the creative frames that shape every post.
 * Each archetype maps to a hook type and provides prompt guidance for the LLM.
 * Consumed by prompts.ts (system prompt archetype table) and the LLM when
 * planning cycles (draftCycle) and generating posts (generatePost).
 */

import type { HookType } from './hooks.js';
import type { PostType } from '@restropulse/shared';

export type RestaurantArchetypeId =
  | 'CHEFS_PICK'
  | 'BEHIND_THE_SCENES'
  | 'SOCIAL_PROOF'
  | 'OFFER_PROMO'
  | 'STAFF_SPOTLIGHT'
  | 'ORIGIN_STORY'
  | 'RECIPE_REVEAL'
  | 'SEASONAL_MENU'
  | 'ORDER_NOW_CTA'
  | 'FOOD_PAIRING'
  | 'CUSTOMER_SPOTLIGHT'
  | 'USER_GENERATED_CONTENT'
  | 'SUSTAINABILITY'
  | 'AWARDS_RECOGNITION'
  | 'HEALTH_DIETARY_SIGNAL'
  | 'VIBE_CHECK'
  | 'EVENT_ANNOUNCEMENT'
  | 'SOUND_OF_THE_KITCHEN'
  | 'CRAVING_CUE'
  | 'SECRET_MENU_UNLOCK'
  | 'THE_GUESSING_GAME'
  | 'ANATOMY_OF_A_DISH'
  | 'SUPPLIER_SHOUTOUT'
  | 'TIMELAPSE_STORY'
  | 'WASTE_NOT'
  | 'THE_REJECTS'
  | 'FESTIVAL_TIE_IN'
  | 'CUISINE_EDUCATION'
  | 'COMMUNITY_POLL'
  | 'MEME_CULTURE'
  | 'CHALLENGE_TREND'
  | 'THIS_OR_THAT'
  | 'INGREDIENT_DEEP_DIVE'
  | 'THE_PERFECT_SITUATION'
  | 'MYTH_BUSTING'
  | 'OCCASION_SPOTLIGHT'
  | 'INSTAGRAMMABLE_MOMENT';

export interface RestaurantArchetype {
  id: RestaurantArchetypeId;
  label: string;
  description: string;
  defaultHookType: HookType;
  /** true = LLM can generate without any restaurant-specific data (cuisine type is sufficient) */
  inputFree: boolean;
  /** false = disabled from cycle planning until real restaurant data is available */
  enabled: boolean;
  /** true = always include at least one post of this archetype in every cycle */
  flagship: boolean;
  fssaiSensitive: boolean;
  reelCompatible: boolean;
  carouselCompatible: boolean;
  preferredPostTypes: PostType[];
  /** true = AI-generated media significantly degrades this archetype's value */
  requiresAuthenticMedia: boolean;
  /** Guidance prompt template for generatePost. Uses {placeholder} notation. */
  promptTemplate: string;
}

export const RESTAURANT_ARCHETYPES: ReadonlyArray<RestaurantArchetype> = [
  {
    id: 'CHEFS_PICK',
    label: "Chef's Pick",
    description: "Showcase a signature or featured dish as the restaurant's crown jewel -- driven by craft, provenance, or technique",
    defaultHookType: 'CURIOSITY_GAP',
    inputFree: false,
    enabled: false,
    flagship: true,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: "Feature the most iconic or beloved {cuisine} dish as {restaurantName}'s signature. Open with a sensory detail -- aroma, texture, or the defining technique. Add a craft or exclusivity angle. Tone: {brandTone}. Close with a soft CTA to visit or order.",
  },
  {
    id: 'BEHIND_THE_SCENES',
    label: 'Behind the Scenes',
    description: 'Reveal the kitchen reality -- prep rituals, rush hour energy, mise en place, sourcing mornings',
    defaultHookType: 'PROCESS_REVEAL',
    inputFree: false,
    enabled: false,
    flagship: true,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: true,
    preferredPostTypes: ['REEL', 'IMAGE'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Show a specific {cuisine} kitchen prep moment -- spice tempering, dough rolling, marination, or dum sealing. Lead with the action, not the result. Make the reader feel the pace and craft of the kitchen. No product pitch in the first line.',
  },
  {
    id: 'SOCIAL_PROOF',
    label: 'Social Proof',
    description: 'Surface authentic external validation -- real reviews, critic write-ups, food blogger content, or customer milestones',
    defaultHookType: 'SOCIAL_PROOF_OPEN',
    inputFree: false,
    enabled: false,
    flagship: true,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'CAROUSEL', 'STORY'],
    requiresAuthenticMedia: true,
    promptTemplate: 'Build a post around this real review: "{customerReview}". Do not just quote it -- construct a caption that carries its emotional tone. Match the dish or moment the reviewer mentions with a strong sensory hook. Keep the reviewer\'s voice audible.',
  },
  {
    id: 'OFFER_PROMO',
    label: 'Offer / Promo',
    description: 'Direct conversion driver -- active discounts, happy hours, combos, loyalty rewards',
    defaultHookType: 'PRICE_ANCHOR',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Announce: {offerDetails} at {restaurantName}, valid {offerValidity}. Lead with the value proposition, not the discount number. Make it feel like a discovery, not a clearance. Add time or quantity scarcity if applicable. Tone: {brandTone}.',
  },
  {
    id: 'STAFF_SPOTLIGHT',
    label: 'Staff Spotlight',
    description: 'Humanise the brand by introducing the people behind the food -- their craft, obsessions, or origin story',
    defaultHookType: 'BEHIND_THE_SCENES',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL'],
    requiresAuthenticMedia: true,
    promptTemplate: "Introduce {staffName}, {staffRole} at {restaurantName}. Highlight one thing they are known for -- a technique they've mastered, a dish they champion, or a detail they obsess over. Warm and personal. 3-4 lines. Close: 'Come in and ask them about it.'",
  },
  {
    id: 'ORIGIN_STORY',
    label: 'Origin Story',
    description: "Tell the heritage of the cuisine or the founding mission -- the tradition it carries, not necessarily this restaurant's history",
    defaultHookType: 'REGIONAL_PRIDE',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: true,
    preferredPostTypes: ['CAROUSEL', 'IMAGE', 'REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: "Tell the heritage story behind {cuisine} cooking -- the historical moment, migration, dynasty, or regional tradition that defines it. Connect it briefly to why {restaurantName} cooks this food. 3-4 lines. Use REGIONAL_PRIDE hook. Do not fabricate this restaurant's founding -- tell the cuisine's story.",
  },
  {
    id: 'RECIPE_REVEAL',
    label: 'Recipe Reveal',
    description: 'Share a simplified, home-recreatable version of a cuisine-typical dish -- builds trust and drives massive saves',
    defaultHookType: 'PROCESS_REVEAL',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: true,
    preferredPostTypes: ['CAROUSEL', 'REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: "Share a simplified 4-6 step home version of a classic {cuisine} dish. Build in a 'chef's secret' at step 3 or 4. Frame as 'our take on the classic, not the exact recipe.' Close: 'Come taste the real thing at {restaurantName}.'",
  },
  {
    id: 'SEASONAL_MENU',
    label: 'Seasonal Menu',
    description: 'Drive urgency around dishes that feel natural to the current season -- monsoon comfort, summer cool, winter warmth',
    defaultHookType: 'CURIOSITY_GAP',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'CAROUSEL', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: "Write a seasonal post for {cuisine} in {city} during {season}. Choose 1-2 dishes that feel natural to this season. Lead with the season's sensory feeling before naming the food. Create craving through context, not product description.",
  },
  {
    id: 'ORDER_NOW_CTA',
    label: 'Order Now CTA',
    description: 'Hard conversion post timed to peak hunger windows -- drives immediate delivery or reservation clicks',
    defaultHookType: 'PRICE_ANCHOR',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: "Conversion post for {restaurantName} ({cuisine}, {city}) timed to {timeOfDay} on a {dayOfWeek}. Pick the most craveable {cuisine} dish for this hour. CTA: 'Order now -- link in bio' (Swiggy/Zomato). Under 3 lines. No fluff -- hunger trigger to action.",
  },
  {
    id: 'FOOD_PAIRING',
    label: 'Food Pairing',
    description: 'Educate diners on complementary combinations -- dish + drink or side -- to upsell naturally while adding value',
    defaultHookType: 'UNEXPECTED_FACT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'CAROUSEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Recommend a well-known {cuisine} pairing -- a dish with its ideal drink, side, or condiment. Explain the contrast or complement in one line (acid cuts fat, sweet balances heat). Educate naturally, upsell subtly. No overt selling language.',
  },
  {
    id: 'CUSTOMER_SPOTLIGHT',
    label: 'Customer Spotlight',
    description: 'Celebrate loyal regulars or memorable guest milestones -- anniversaries, proposals, birthday parties',
    defaultHookType: 'SOCIAL_PROOF_OPEN',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL'],
    requiresAuthenticMedia: true,
    promptTemplate: 'Celebrate {customerOccasion} at {restaurantName}. Reference the specific meal or moment -- personal and warm, not generic. End with a sincere thank-you from the team. 3-4 lines. Do not make it sound like marketing.',
  },
  {
    id: 'USER_GENERATED_CONTENT',
    label: 'User-Generated Content',
    description: 'Curate and reshare organic content from customers who tagged the restaurant -- maximum authenticity, zero production cost',
    defaultHookType: 'SOCIAL_PROOF_OPEN',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL', 'STORY'],
    requiresAuthenticMedia: true,
    promptTemplate: "Reshare caption for {restaurantName} featuring content from @{customerHandle}. Credit the creator in the first line. Add one line in the restaurant's own voice. Keep it brief -- the customer's content is the hero, not the caption.",
  },
  {
    id: 'SUSTAINABILITY',
    label: 'Sustainability',
    description: 'Project ethical sourcing values, farm-to-table supply chains, or eco-conscious kitchen practices',
    defaultHookType: 'BEHIND_THE_SCENES',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'CAROUSEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Write a local-sourcing post for a {cuisine} restaurant in {city}. Reference seasonal produce, local market networks, or reduced-waste kitchen practices natural to this region. Specific and factual -- no vague green language. 2-3 lines.',
  },
  {
    id: 'AWARDS_RECOGNITION',
    label: 'Awards & Recognition',
    description: 'Broadcast institutional credibility -- industry awards, top rankings, press placements, certification badges',
    defaultHookType: 'SOCIAL_PROOF_OPEN',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: "Announce {awardName} awarded to {restaurantName} by {awardSource}. Lead with gratitude, not boasting. Briefly acknowledge the team's effort. Close with a thank-you to customers. 3 lines maximum. Warm, not self-congratulatory.",
  },
  {
    id: 'HEALTH_DIETARY_SIGNAL',
    label: 'Dietary Highlight',
    description: 'Signal inclusive dining options -- vegan, Jain, gluten-free, keto, high-protein -- factual labelling only',
    defaultHookType: 'UNEXPECTED_FACT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: true,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'CAROUSEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Highlight a dish in {cuisine} that is naturally {dietaryType} (vegan / Jain / gluten-free / high-protein / keto-friendly). State only factual attributes -- zero health benefit claims. FSSAI-compliant framing. 2-3 lines.',
  },
  {
    id: 'VIBE_CHECK',
    label: 'Vibe Check',
    description: 'Sell the atmosphere, not the food -- lighting, music, architectural mood, the feeling of being in the space',
    defaultHookType: 'PATTERN_INTERRUPT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['REEL', 'IMAGE', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Describe the sensory experience of being inside a {cuisine} restaurant in {city} with {seatingType} seating -- lighting quality, ambient sound, temperature feel, the mood of the room at its best hour. Do not mention food. Sell only the state of being there. 2-3 lines. Tone: {brandTone}.',
  },
  {
    id: 'EVENT_ANNOUNCEMENT',
    label: 'Event Announcement',
    description: 'Generate awareness and bookings for live music, trivia nights, pop-up takeovers, themed dinners',
    defaultHookType: 'FESTIVAL_MOMENT',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'STORY', 'CAROUSEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Announce {eventName} at {restaurantName} on {eventDate} at {eventTime}. Describe the act or theme in one line. Add a reservation or RSVP urgency note. Write it as an invitation, not a press release. 3-4 lines. Tone: {brandTone}.',
  },
  {
    id: 'SOUND_OF_THE_KITCHEN',
    label: 'Sound of the Kitchen',
    description: 'Pure ASMR sensory content -- no music, no voiceover, just raw kitchen soundscapes that trigger appetite',
    defaultHookType: 'PROCESS_REVEAL',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Describe one specific {cuisine} kitchen sound -- a sizzling tadka, dough slapping a surface, bread cracking open, a wok scrape. Caption: 1-2 lines maximum. Let the sound carry the post. Do not name a dish -- let the context do it. No CTA.',
  },
  {
    id: 'CRAVING_CUE',
    label: 'Craving Cue',
    description: 'Extreme macro visual triggers -- slow-motion, close-up food footage engineered for maximum appetite stimulation',
    defaultHookType: 'TRANSFORMATION_REVEAL',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['REEL', 'VIDEO'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Write 1-2 lines for a slow-motion macro visual of the most sensory moment of a {cuisine} dish -- a sauce pour, crust crack, cheese pull, or steam release. Heighten the visual, do not describe it literally. Pure desire trigger -- no CTA needed.',
  },
  {
    id: 'SECRET_MENU_UNLOCK',
    label: 'Secret Menu Unlock',
    description: 'Gamify the dining experience by rewarding digital followers with unlisted menu items via a code word',
    defaultHookType: 'CURIOSITY_GAP',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: "Create intrigue around a hidden item at {restaurantName} without naming it in line 1. Reveal the unlock code '{codeWord}' in line 2. The item is {secretItemName} -- describe it in one enticing line. End: 'Valid this week only.'",
  },
  {
    id: 'THE_GUESSING_GAME',
    label: 'The Guessing Game',
    description: 'Cryptic interactive teaser posts that invite the audience to identify a dish or ingredient -- drives comment volume',
    defaultHookType: 'CURIOSITY_GAP',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Write a guessing game post for a {cuisine} restaurant. The concealed dish is {dishName} -- do not reveal it. Give exactly one cryptic clue tied to its key ingredient, origin, or preparation method. Invite guesses in the comments. Playful tone, under 2 lines.',
  },
  {
    id: 'ANATOMY_OF_A_DISH',
    label: 'Anatomy of a Dish',
    description: 'A layered breakdown mapping the structural and flavour components of a signature dish',
    defaultHookType: 'UNEXPECTED_FACT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['CAROUSEL', 'IMAGE'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Break down a signature {cuisine} dish into 5-7 structural layers from base to finish. One line per component -- name it and explain its role. Infographic framing. Educational but accessible, no jargon.',
  },
  {
    id: 'SUPPLIER_SHOUTOUT',
    label: 'Supplier Shoutout',
    description: 'Humanise the supply chain by celebrating the local farmers, artisans, or market vendors behind the ingredients',
    defaultHookType: 'BEHIND_THE_SCENES',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'CAROUSEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Celebrate the kind of artisan or local supplier that powers {cuisine} cooking in {city} -- a spice bazaar, urban farm, dairy producer, or bread baker. Humanise the supply chain with a regional reference. Do not fabricate a named individual -- keep it to the category and region.',
  },
  {
    id: 'TIMELAPSE_STORY',
    label: 'Timelapse Story',
    description: 'Time-compressed window into a full operational stretch -- dining room filling, kitchen ramping up, service winding down',
    defaultHookType: 'TRANSFORMATION_REVEAL',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['REEL', 'VIDEO'],
    requiresAuthenticMedia: true,
    promptTemplate: "Caption for a timelapse of {restaurantName}'s dining room going from empty to full on a {dayOfWeek} evening. 2-3 lines. Lead with the visual transformation. Capture the energy shift from quiet prep to full service.",
  },
  {
    id: 'WASTE_NOT',
    label: 'Waste Not',
    description: 'Show back-of-house resourcefulness -- creative zero-waste engineering that repurposes every part of an ingredient',
    defaultHookType: 'BEHIND_THE_SCENES',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Show how a {cuisine} kitchen creatively repurposes a specific by-product -- citrus peels as bitters, spent spices as oil infusion, bones as stock base. One specific, concrete example told concisely. Craft-forward framing, not environmental preaching.',
  },
  {
    id: 'THE_REJECTS',
    label: 'The Rejects',
    description: "Radical transparency into R&D failures -- experiments that didn't make the cut, humanising the creative process",
    defaultHookType: 'PATTERN_INTERRUPT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'STORY', 'REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: "Invent a plausible failed R&D experiment for a {cuisine} kitchen. Format: 'R&D Log #{n}: [invented dish name]. [What went wrong in one line]. The team said [verdict]. Back to the drawing board.' Tone: self-deprecating, transparent, humanising.",
  },
  {
    id: 'FESTIVAL_TIE_IN',
    label: 'Festival Tie-in',
    description: "Leverage cultural events and holidays by connecting the festival's emotional core to food and community",
    defaultHookType: 'FESTIVAL_MOMENT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'STORY', 'REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: "Write a {festivalName} post for a {cuisine} restaurant in {city}. Connect the festival's emotional core to food, family, and memory -- not just a greeting. Reference a dish, tradition, or sensory detail tied to the festival in {cuisine} culture. 3-4 lines. Culturally sensitive framing required.",
  },
  {
    id: 'CUISINE_EDUCATION',
    label: 'Cuisine Education',
    description: 'Culturally enriching content teaching the history, geography, technique, or etiquette of the cuisine style',
    defaultHookType: 'UNEXPECTED_FACT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['CAROUSEL', 'IMAGE'],
    requiresAuthenticMedia: false,
    promptTemplate: "Teach one genuinely surprising fact about {cuisine} cooking -- a technique, historical context, or food science detail most people don't know. Lead with the unexpected fact. Accessible language, no jargon. 3-4 lines. End with why it changes how the food tastes.",
  },
  {
    id: 'COMMUNITY_POLL',
    label: 'Community Poll',
    description: 'High-engagement binary questions that drive taps, votes, and comments on personal food preferences',
    defaultHookType: 'ENGAGEMENT_PROMPT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: false,
    preferredPostTypes: ['STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: "Write an Instagram Stories poll for {cuisine} food fans. Choose a binary, genuinely divisive preference -- something fans have strong opinions about. Format: '[Option A] or [Option B]? Vote below.' One line maximum. Emoji optional.",
  },
  {
    id: 'MEME_CULTURE',
    label: 'Meme Culture',
    description: 'Relatable food or restaurant-industry humor adapted to current viral formats',
    defaultHookType: 'PATTERN_INTERRUPT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Adapt a currently relatable dining or food experience scenario into a short, shareable post for {restaurantName} ({cuisine}). The punchline must be specific to the dining experience -- not generic. Under 3 lines. Lean slightly lighter in tone than {brandTone} normally allows.',
  },
  {
    id: 'CHALLENGE_TREND',
    label: 'Challenge / Trend',
    description: 'Participate in internet challenges, trending audio formats, or viral digital trends to ride algorithm waves',
    defaultHookType: 'PATTERN_INTERRUPT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['REEL'],
    requiresAuthenticMedia: false,
    promptTemplate: "Write a caption for {restaurantName} participating in {trendName}. Wholesome and natural -- not forced. Reference the challenge name if currently trending. 1-2 lines. The reel carries the content; the caption anchors it with the restaurant's voice.",
  },
  {
    id: 'THIS_OR_THAT',
    label: 'This or That',
    description: 'Binary tournament-style choice posts designed to split opinion and drive high comment volume',
    defaultHookType: 'ENGAGEMENT_PROMPT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['IMAGE', 'STORY', 'CAROUSEL'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Create a binary debate post for a {cuisine} restaurant. Pick two iconic dishes or preparations that fans genuinely argue about. Frame it as a battle or loyalty test. Invite comments to declare a side. 1-2 lines of copy + a prompt for a side-by-side visual.',
  },
  {
    id: 'INGREDIENT_DEEP_DIVE',
    label: 'Ingredient Deep Dive',
    description: 'Nerd out on a single core component -- sourcing region, botanical history, quality markers, flavour chemistry',
    defaultHookType: 'UNEXPECTED_FACT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['CAROUSEL', 'IMAGE'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Deep-dive into {ingredient}, a core component of {cuisine}. Cover: sourcing region, why quality variation matters, how it alters the final dish. Include one genuinely surprising fact. 4-5 lines. Works best in infographic carousel format.',
  },
  {
    id: 'THE_PERFECT_SITUATION',
    label: 'The Perfect Situation',
    description: 'Contextual lifestyle marketing matching menu items to specific emotional states or relatable human scenarios',
    defaultHookType: 'PATTERN_INTERRUPT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Match a specific relatable human moment ({situation}: post-gym, survived a deadline, rainy afternoon, Sunday laziness) to {cuisine} food at {restaurantName}. Warm and wry -- the situation does the selling. 2-3 lines. No direct product mention required.',
  },
  {
    id: 'MYTH_BUSTING',
    label: 'Myth Busting',
    description: 'Correct common misconceptions about food preparation, regional traditions, or ingredient properties',
    defaultHookType: 'UNEXPECTED_FACT',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: false,
    carouselCompatible: true,
    preferredPostTypes: ['CAROUSEL', 'IMAGE'],
    requiresAuthenticMedia: false,
    promptTemplate: "Debunk a common misconception about {cuisine} cooking. Format: 'Myth: [widely believed wrong thing]. Truth: [specific, surprising correction].' The truth must be counter-intuitive and specific. 3-4 lines. Shareable and authoritative in tone.",
  },
  {
    id: 'OCCASION_SPOTLIGHT',
    label: 'Occasion Spotlight',
    description: 'Target occasion diners -- dates, proposals, anniversaries, business lunches -- by selling the emotional experience, not the menu',
    defaultHookType: 'CURIOSITY_GAP',
    inputFree: true,
    enabled: true,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL', 'STORY'],
    requiresAuthenticMedia: false,
    promptTemplate: 'Write an occasion dining post for {restaurantName} targeting {occasion} (date night / anniversary / proposal / family milestone / business dinner). Lead with the emotional experience -- not the menu. Include a reservation CTA. 3-4 lines. Tone: {brandTone}.',
  },
  {
    id: 'INSTAGRAMMABLE_MOMENT',
    label: 'Instagrammable Moment',
    description: 'Showcase specific visual set-pieces designed for customer photography -- the customer is the protagonist, not the restaurant',
    defaultHookType: 'PATTERN_INTERRUPT',
    inputFree: false,
    enabled: false,
    flagship: false,
    fssaiSensitive: false,
    reelCompatible: true,
    carouselCompatible: false,
    preferredPostTypes: ['IMAGE', 'REEL'],
    requiresAuthenticMedia: true,
    promptTemplate: "Write a post for {restaurantName}'s signature visual element: {visualFeature} (e.g. fog cocktail, neon sign, dramatic plating reveal). Position the customer as the protagonist -- 'you will want to photograph this.' Include a subtle 'tag us' CTA at the close.",
  },
];

/** Returns all currently enabled archetypes. */
export function getEnabledArchetypes(): RestaurantArchetype[] {
  return RESTAURANT_ARCHETYPES.filter(a => a.enabled);
}

/** Returns enabled archetypes designated as flagship (always included in every cycle). */
export function getFlagshipArchetypes(): RestaurantArchetype[] {
  return RESTAURANT_ARCHETYPES.filter(a => a.enabled && a.flagship);
}

/** @deprecated Use getEnabledArchetypes() */
export function getWeeklyArchetypeMix(): RestaurantArchetype[] {
  return getEnabledArchetypes();
}
